
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jun 25 2025 23:52:18 PDT (Jun 26 2025 06:52:18 UTC)

// Verification Directory fv/priority_encoder_8 

module priority_encoder_8(in, en, out, valid);
  input [7:0] in;
  input en;
  output [2:0] out;
  output valid;
  wire [7:0] in;
  wire en;
  wire [2:0] out;
  wire valid;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_14, n_15;
  CLKINVX1 g311(.A (n_15), .Y (out[0]));
  OAI21X1 g312__2398(.A0 (in[7]), .A1 (n_14), .B0 (en), .Y (n_15));
  NOR2X1 g314__5107(.A (in[6]), .B (n_11), .Y (n_14));
  AOI21X1 g315__6260(.A0 (n_2), .A1 (n_6), .B0 (n_0), .Y (out[1]));
  AND2X2 g313__4319(.A (en), .B (n_10), .Y (valid));
  NOR2X1 g318__8428(.A (in[5]), .B (n_9), .Y (n_11));
  OR4X2 g316__5526(.A (in[0]), .B (in[1]), .C (n_4), .D (n_7), .Y
       (n_10));
  NOR2X1 g319__6783(.A (in[4]), .B (n_5), .Y (n_9));
  AND2X2 g317__3680(.A (en), .B (n_7), .Y (out[2]));
  OR3X1 g320__1617(.A (in[5]), .B (in[4]), .C (n_3), .Y (n_6));
  AOI21X1 g322__2802(.A0 (in[1]), .A1 (n_1), .B0 (in[3]), .Y (n_5));
  INVX1 g323(.A (n_3), .Y (n_4));
  OR4X2 g321__1705(.A (in[6]), .B (in[7]), .C (in[4]), .D (in[5]), .Y
       (n_7));
  NOR2X1 g324__5122(.A (in[2]), .B (in[3]), .Y (n_3));
  NOR2X1 g325__8246(.A (in[6]), .B (in[7]), .Y (n_2));
  CLKINVX1 g326(.A (in[2]), .Y (n_1));
  CLKINVX1 g327(.A (en), .Y (n_0));
endmodule

